import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = resolve(packageRoot, "src/tokens.json");
const typescriptPath = resolve(packageRoot, "src/tokens.ts");
const cssPath = resolve(packageRoot, "src/tokens.css");

const manifest = JSON.parse(await readFile(manifestPath, "utf8"));

const groupNames = {
  colors: "color",
  spacing: "space",
  radii: "radius",
  fontSizes: "text",
  fontWeights: "weight",
  lineHeights: "leading",
  motion: "motion",
  shadows: "shadow",
  zIndex: "z",
  breakpoints: "breakpoint",
};

const toKebab = (value) =>
  value.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

const typescript = `// Generated by scripts/tokens.mjs. Edit tokens.json instead.\nexport const designTokens = ${JSON.stringify(manifest, null, 2)} as const;\n\nexport type DesignTokens = typeof designTokens;\n`;

const cssDeclarations = Object.entries(manifest).flatMap(([group, values]) =>
  Object.entries(values).map(
    ([name, value]) =>
      `  --mi-${groupNames[group] ?? toKebab(group)}-${toKebab(name)}: ${value};`,
  ),
);
const css = `/* Generated by scripts/tokens.mjs. Edit tokens.json instead. */\n:root {\n${cssDeclarations.join("\n")}\n}\n`;

const contrastPairs = [
  ["ink", "canvas", 4.5],
  ["ink", "surface", 4.5],
  ["mutedForeground", "canvas", 4.5],
  ["mutedForeground", "surface", 4.5],
  ["ink", "accent", 4.5],
  ["successForeground", "successSurface", 4.5],
  ["warningForeground", "warningSurface", 4.5],
  ["dangerForeground", "dangerSurface", 4.5],
  ["infoForeground", "infoSurface", 4.5],
];

const channel = (value) => {
  const normalized = value / 255;
  return normalized <= 0.04045
    ? normalized / 12.92
    : ((normalized + 0.055) / 1.055) ** 2.4;
};

const luminance = (hex) => {
  const value = hex.slice(1);
  const [red, green, blue] = [0, 2, 4].map((index) =>
    channel(Number.parseInt(value.slice(index, index + 2), 16)),
  );
  return 0.2126 * red + 0.7152 * green + 0.0722 * blue;
};

const contrast = (foreground, background) => {
  const light = Math.max(luminance(foreground), luminance(background));
  const dark = Math.min(luminance(foreground), luminance(background));
  return (light + 0.05) / (dark + 0.05);
};

const checkContrast = () => {
  for (const [foreground, background, minimum] of contrastPairs) {
    const ratio = contrast(
      manifest.colors[foreground],
      manifest.colors[background],
    );
    if (ratio < minimum) {
      throw new Error(
        `${foreground} on ${background} has ${ratio.toFixed(2)}:1 contrast; expected ${minimum}:1.`,
      );
    }
  }
};

const mode = process.argv[2] ?? "check";
checkContrast();

if (mode === "write") {
  await Promise.all([
    writeFile(typescriptPath, typescript),
    writeFile(cssPath, css),
  ]);
  console.log("Generated tokens.ts and tokens.css; contrast pairs pass.");
} else if (mode === "check") {
  const [currentTypescript, currentCss] = await Promise.all([
    readFile(typescriptPath, "utf8"),
    readFile(cssPath, "utf8"),
  ]);
  if (currentTypescript !== typescript || currentCss !== css) {
    throw new Error(
      "Generated token files are stale. Run pnpm tokens:generate.",
    );
  }
  console.log("Token files are current; contrast pairs pass.");
} else {
  throw new Error(`Unknown mode: ${mode}. Use write or check.`);
}
