apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.minirospeer'
version = '0.1.0'
android {
  namespace 'expo.modules.minirospeer'
  defaultConfig { versionCode 1; versionName '0.1.0' }
}
dependencies {
  implementation 'com.google.android.gms:play-services-nearby:19.3.0'
}
