/* Built with a unique cache version after next build. Never cache private HTML/API responses. */
const VERSION = "miniros-__BUILD_ID__";
const ASSETS = null; // Injected by build-pwa; prevents truncated manifests reporting ready.
const SHELL = "/offline";
const OFFLINE_PATH =
  /^\/(offline|sync|install|help|more|profile|pos|inventory|shifts|schedule)(\/|$)/;
const REQUIRED = [SHELL, "/manifest.webmanifest", "/icons/icon-192.png"];
const matchOptions = { ignoreVary: true };
function validManifest(manifest) {
  return (
    manifest &&
    `miniros-${manifest.version}` === VERSION &&
    Array.isArray(manifest.assets) &&
    manifest.assets.length > 0 &&
    (!ASSETS ||
      (manifest.assets.length === ASSETS.length &&
        ASSETS.every((path) => manifest.assets.includes(path)))) &&
    manifest.assets.every(
      (path) =>
        typeof path === "string" &&
        !path.includes("..") &&
        /^\/_next\/static\/[\w/().\[\]-]+\.(js|css|woff2?)$/.test(path),
    ) &&
    (manifest.shell === undefined || manifest.shell === "/pwa-shell.html")
  );
}
function shellBuild(html) {
  const marker = html.match(
    /<meta name="miniros-build" content="([\w-]+)"\s*\/?\s*>/,
  )?.[1];
  const flight = html.replaceAll('\\"', '"').match(/"b":"([\w-]+)"/)?.[1];
  // Reject a marker added to HTML generated by a different Next build.
  if (marker && flight && marker !== flight) return undefined;
  return marker ?? flight;
}
self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 60000);
      // Cache operations cannot be cancelled, but must not hold installation
      // open after its deadline. Observe their results and release listeners.
      const step = (operation) =>
        new Promise((resolve, reject) => {
          const signal = controller.signal;
          const abort = () => reject(signal.reason);
          signal.throwIfAborted();
          signal.addEventListener("abort", abort, { once: true });
          Promise.resolve()
            .then(operation)
            .then(resolve, reject)
            .finally(() => signal.removeEventListener("abort", abort));
        });
      try {
        const response = await step(() =>
          fetch("/pwa-assets.json", {
            cache: "no-store",
            signal: controller.signal,
          }),
        );
        if (!response.ok || response.redirected)
          throw new Error("Offline asset list unavailable");
        const manifest = await step(() => response.json());
        if (!validManifest(manifest)) throw new Error("Offline build mismatch");
        const cache = await step(() => caches.open(VERSION));
        const paths = [...new Set([...REQUIRED, ...manifest.assets])];
        for (let index = 0; index < paths.length; index += 4) {
          await Promise.all(
            paths.slice(index, index + 4).map(async (path) => {
              const downloaded = await step(() =>
                fetch(path === SHELL ? (manifest.shell ?? path) : path, {
                  cache: "no-store",
                  signal: controller.signal,
                }),
              );
              if (
                !downloaded.ok ||
                downloaded.redirected ||
                (path !== SHELL &&
                  downloaded.headers.get("content-type")?.includes("text/html"))
              )
                throw new Error(`Offline download failed: ${path}`);
              if (
                path === SHELL &&
                shellBuild(await step(() => downloaded.clone().text())) !==
                  manifest.version
              )
                throw new Error("Offline shell build mismatch");
              await step(() => cache.put(path, downloaded));
            }),
          );
        }
        for (const path of paths) {
          if (!(await step(() => cache.match(path, matchOptions)))?.ok)
            throw new Error(`Offline file missing: ${path}`);
        }
        await step(() =>
          cache.put(
            "/pwa-assets.json",
            new Response(JSON.stringify(manifest), {
              headers: { "Content-Type": "application/json" },
            }),
          ),
        );
      } finally {
        clearTimeout(timer);
        controller.abort();
      }
    })(),
  );
});
self.addEventListener("activate", (event) => {
  // Keep older build caches and every local journal intact.
  event.waitUntil(self.clients.claim());
});
self.addEventListener("message", (event) => {
  if (event.data === "ACTIVATE_UPDATE") self.skipWaiting();
  if (event.data === "CHECK_OFFLINE_READY")
    event.waitUntil(
      (async () => {
        const started = Date.now();
        let result;
        try {
          const cache = await caches.open(VERSION);
          const response = await cache.match("/pwa-assets.json", matchOptions);
          const manifest = response ? await response.json() : undefined;
          const valid = validManifest(manifest);
          const paths = [
            ...new Set([...REQUIRED, ...(valid ? manifest.assets : [])]),
          ];
          const stored = await Promise.all(
            paths.map((path) => cache.match(path, matchOptions)),
          );
          const missingFiles = paths.filter((_, index) => !stored[index]?.ok);
          const shell = stored[0];
          if (
            shell &&
            shellBuild(await shell.text()) !== manifest?.version &&
            !missingFiles.includes(SHELL)
          )
            missingFiles.push(SHELL);
          result = {
            ready: Boolean(valid) && missingFiles.length === 0,
            missingFiles,
            ...(valid
              ? {}
              : {
                  code: "cache",
                  error: "Offline asset manifest is missing or invalid.",
                }),
          };
        } catch (failure) {
          result = {
            ready: false,
            code: failure?.name === "SyntaxError" ? "cache" : "storage",
            error:
              failure instanceof Error
                ? failure.message
                : "Offline cache unavailable.",
          };
        }
        event.ports[0]?.postMessage({
          ...result,
          contractVersion: 2,
          version: VERSION,
          durationMs: Date.now() - started,
        });
      })(),
    );
});
self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== "GET" || url.origin !== self.location.origin)
    return;
  if (
    url.pathname.startsWith("/_next/static/") ||
    url.pathname.startsWith("/icons/") ||
    url.pathname === "/manifest.webmanifest"
  ) {
    event.respondWith(
      (async () =>
        (await (
          await caches.open(VERSION)
        ).match(event.request, matchOptions)) ??
        (url.pathname.startsWith("/_next/static/")
          ? await caches.match(event.request, matchOptions)
          : undefined) ??
        fetch(event.request))(),
    );
    return;
  }
  if (
    event.request.mode === "navigate" &&
    (url.pathname === "/" || OFFLINE_PATH.test(url.pathname))
  ) {
    event.respondWith(
      (async () => {
        try {
          // A slow page or a server error is not an offline navigation.
          // Only fall back to saved shifts when the network request fails.
          return await fetch(event.request);
        } catch {
          return (
            (await (await caches.open(VERSION)).match(SHELL, matchOptions)) ??
            new Response(
              "This device was not prepared for offline use. Reconnect to open MINIROS.",
              { status: 503, headers: { "Content-Type": "text/plain" } },
            )
          );
        }
      })(),
    );
  }
});
